import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: "#F8F9FA",
    },
    header: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 16,
      backgroundColor: "#FFF",
      borderBottomWidth: 1,
      borderBottomColor: "#F0F0F0",
    },
    title: {
      fontSize: 24,
      fontWeight: "bold",
      color: "#333",
    },
    addButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      overflow: "hidden",
    },
    addButtonGradient: {
      width: "100%",
      height: "100%",
      justifyContent: "center",
      alignItems: "center",
    },
    listContent: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 24,
    },
    petCardContainer: {
      marginVertical: 8,
    },
    petCard: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#FFF",
      borderRadius: 16,
      padding: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 2,
    },
    petImageContainer: {
      width: 60,
      height: 60,
      borderRadius: 30,
      overflow: "hidden",
      backgroundColor: "#F0F0F0",
    },
    petImage: {
      width: "100%",
      height: "100%",
    },
    petInfo: {
      flex: 1,
      marginLeft: 16,
    },
    petNome: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 4,
    },
    petRaca: {
      fontSize: 14,
      color: "#666",
      marginBottom: 2,
    },
    petIdade: {
      fontSize: 14,
      color: "#999",
    },
    optionsButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      justifyContent: "center",
      alignItems: "center",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      justifyContent: "center",
      alignItems: "center",
    },
    optionsModalContainer: {
      width: "80%",
      maxWidth: 300,
    },
    optionsModal: {
      backgroundColor: "#FFF",
      borderRadius: 16,
      overflow: "hidden",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 5,
    },
    optionsHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: "#F0F0F0",
    },
    optionsTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: "#333",
    },
    closeButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      justifyContent: "center",
      alignItems: "center",
    },
    optionItem: {
      flexDirection: "row",
      alignItems: "center",
      padding: 16,
      borderBottomWidth: 1,
      borderBottomColor: "#F0F0F0",
    },
    optionText: {
      fontSize: 16,
      color: "#333",
      marginLeft: 16,
    },
    confirmModalContainer: {
      width: "90%",
      maxWidth: 340,
    },
    confirmModal: {
      backgroundColor: "#FFF",
      borderRadius: 16,
      padding: 24,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 5,
    },
    confirmTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#333",
      marginBottom: 16,
    },
    confirmText: {
      fontSize: 16,
      color: "#666",
      marginBottom: 24,
      lineHeight: 22,
    },
    confirmButtons: {
      flexDirection: "row",
      justifyContent: "flex-end",
    },
    confirmButton: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 8,
      marginLeft: 12,
    },
    cancelButton: {
      backgroundColor: "#F0F0F0",
    },
    deleteButton: {
      backgroundColor: "#F44336",
    },
    cancelButtonText: {
      fontSize: 16,
      color: "#333",
      fontWeight: "500",
    },
    deleteButtonText: {
      fontSize: 16,
      color: "#FFF",
      fontWeight: "500",
    },
    detailsModalOverlay: {
      flex: 1,
      backgroundColor: "#F8F9FA",
    },
    detailsModalContainer: {
      flex: 1,
    },
    detailsCloseButton: {
      position: "absolute",
      top: 40,
      right: 16,
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: "rgba(0, 0, 0, 0.3)",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 10,
    },
    petDetailsHeader: {
      height: 250,
      position: "relative",
    },
    petDetailsImage: {
      width: "100%",
      height: "100%",
    },
    petDetailsGradient: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      height: 100,
      justifyContent: "flex-end",
      paddingHorizontal: 16,
      paddingBottom: 16,
    },
    petDetailsName: {
      fontSize: 28,
      fontWeight: "bold",
      color: "#FFF",
    },
    petDetailsContent: {
      flex: 1,
      padding: 16,
    },
    petDetailItem: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 16,
    },
    petDetailIconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: "rgba(255, 122, 0, 0.1)",
      justifyContent: "center",
      alignItems: "center",
      marginRight: 16,
    },
    petDetailLabel: {
      fontSize: 14,
      color: "#666",
    },
    petDetailValue: {
      fontSize: 16,
      fontWeight: "500",
      color: "#333",
    },
    petObservacoes: {
      marginTop: 8,
      padding: 16,
      backgroundColor: "#FFF",
      borderRadius: 12,
      borderWidth: 1,
      borderColor: "#F0F0F0",
    },
    petObservacoesLabel: {
      fontSize: 16,
      fontWeight: "500",
      color: "#333",
      marginBottom: 8,
    },
    petObservacoesText: {
      fontSize: 14,
      color: "#666",
      lineHeight: 20,
    },
    petDetailsActions: {
      flexDirection: "row",
      justifyContent: "space-around",
      marginTop: 24,
      paddingTop: 16,
      borderTopWidth: 1,
      borderTopColor: "#F0F0F0",
    },
    petDetailsAction: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 8,
      paddingHorizontal: 16,
    },
    petDetailsActionText: {
      fontSize: 16,
      color: "#666",
      marginLeft: 8,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "#F8F9FA",
    },
    loadingText: {
      marginTop: 12,
      fontSize: 16,
      color: "#666",
    },
    emptyContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      paddingHorizontal: 32,
      paddingVertical: 60,
    },
    emptyTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: "#333",
      marginTop: 16,
      marginBottom: 8,
    },
    emptyText: {
      fontSize: 16,
      color: "#666",
      textAlign: "center",
      marginBottom: 24,
    },
    emptyButton: {
      height: 48,
      borderRadius: 24,
      overflow: "hidden",
      width: "80%",
    },
    emptyButtonGradient: {
      width: "100%",
      height: "100%",
      justifyContent: "center",
      alignItems: "center",
    },
    emptyButtonText: {
      fontSize: 16,
      fontWeight: "bold",
      color: "#FFF",
    },
  })
  
  export default styles;